version: '3.8'
services:
  workspace:
    build:
      context: resources/docker/workspace
      args:
        PUID: "${PUID:-1000}"
        PGID: "${PGID:-1000}"
    volumes:
      - .:/var/www/html
    tty: true
