name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - '*'

jobs:
  build:

    strategy:
      matrix:
        php:
          - '7.3'
          - '7.4'
          - '8.0'
        laravel:
          - '7'
          - '8'


    runs-on: ubuntu-latest

    name: 'Laravel ${{ matrix.laravel }} on PHP ${{ matrix.php }}'
    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Validate composer
      run: composer validate

    - name: Install dependencies, lock Laravel version
      run: composer require laravel/framework:^${{ matrix.laravel }} --prefer-dist --no-progress

    - name: Run phpstan
      run: composer phpstan
    
    - name: Run PHP CS Fixer
      run: composer php-cs-fixer -- --dry-run --stop-on-violation
    
    - name: Run tests
      run: composer phpunit
