name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run phpstan
      run: composer phpstan
    
    - name: Run PHP CS Fixer
      run: composer php-cs-fixer -- --dry-run --stop-on-violation
    
    - name: Run tests
      run: composer phpunit
